### ISSUE TITLE
Skipping Unassociated Glycan Residues in find_glycans()

### ISSUE THREAD

**Issue by Monikerton** [ibmm-unibe-ch/glycosylator#6]
Hello, 

I'm having an issue with find_glycans() where glycan residues cannot be associated and trying to think of a way to deal with them. Specifically, I've found a few glycans from the PDB which don't have glycans attached to the actual product. 

Take for example the Asymmetric Unit for 3I27: https://www.rcsb.org/3d-view/3I27/0. Trying to run this through glycosylator:

```
import glycosylator as gl 

filename = 'mmcif_data/3I27.cif'
prots = gl.Protein.from_cif(filename)
prots.find_glycans()
```

Along with the typical PDB Construction Warnings, I'm encountering this error: `RuntimeError: Cannot infer glycan association for at least one of [Residue(SID, 1001)]`. After examining the structure in the PDB, it doesn't seem like this residue is attached to any part of the chain, so I assume there isn't sufficient data indicating its attachment.

![image](https://github.com/user-attachments/assets/72596f66-c759-4899-abb6-e26a84305aee)

Given this, I’d like to simply skip over glycans that have no associations when searching for them. Would it be possible to introduce a new keyword to bypass such cases, or do you have any other recommendations? Thanks!

**Comment by NoahHenrikKleinschmidt** [comment]
Hi @Monikerton 

What an interesting case you have there! I never expected to find sugars as part of attached glycans and as ligands in the same system. The good news is this is relatively easy to make happen! I added two new arguments to `find_glycans`: 
- `strict`, which can be set to `False` to allow Glycosylator to ignore glycans that cannot be associated with a glycan chain or residue anchor
- `only_allow_anchors`, which can be used to restrict the search for anchors to only specific types of residues, which may also help prevent mistaken identification of ligands within binding pockets as glycans attached to some random amino acid

I pushed the changes on the `dev` branch so if you clone and install from source you can immediately infer your glycans now! 

So, when I downloaded your PDB file I did the following:

```python
import glycosylator as gl

protein = gl.Protein.from_pdb("3i27.pdb")

# make sure we have proper connectivity
protein.apply_standard_bonds()

# now find the glycans but make sure to only get N- or O-linked ones
# while ignoring anything else
glycans = protein.find_glycans(strict=False, only_allow_anchors=["ASN", "SER"])
```

If I then visualize the protein in Py3dmol I get the SID to be separate and not considered one of the glycans (since there is no red stick representation underlying the transparent green-spheres of SID)

```python
v = protein.py3dmol(glycans=True, glycan_color="red", color="white")
v.add(protein.get_residue("SID"), {"sphere": {"opacity": 0.8, "color": "limegreen"}})
v.show()
```

![image](https://github.com/user-attachments/assets/4543bd92-2747-43af-b5af-f84878eba87a)

Specifically, the glycans I could identify had the following structures (I didn't bother double checking with the file in 3D 😅 )

<details>
<summary>Code to make the figure</summary>

```python
import matplotlib.pyplot as plt
from matplotlib_autolayout.autolayout import autolayout

fig = plt.figure(figsize=(3.5, 3.5), dpi=300)
for i, glycan in enumerate(glycans.values()):
    ax = fig.add_subplot(title=f"glycan {i+1}")
    glycan.draw2d(ax=ax)
autolayout(fig, {"count": 5, "direction": "row", "margin": 0.05})
plt.tight_layout()
plt.show()
```
</details>

![image](https://github.com/user-attachments/assets/99bc4fc8-6d87-4e6e-9df7-a0919b6d53aa)


I hope this helps :-)

Cheers, Noah ☀️

**Comment by Monikerton** [comment]
Just checked -- this works for me! Thanks so much!
